name: Docker Build and Push

on:
  push:
    branches: [release]
  pull_request:
    branches: [release]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker build -t gejinli/apps:$(date +%Y%m) .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push gejinli/apps:$(date +%Y%m)
